services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - LOCAL_LLM_BASE_URL=${LOCAL_LLM_BASE_URL}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
